// CHALLENGES
export const GET_CHALLENGES = 'GET_CHALLENGES';
export const GET_CHALLENGE = 'GET_CHALLENGE';
export const ADD_CHALLENGE = 'ADD_CHALLENGE';

// EXERCISES
export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISE = 'GET_EXERCISE';
export const ADD_EXERCISE = 'ADD_EXERCISE';


// LOGIN & REGISTER
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

